# from: https://circleci.com/orbs/registry/orb/circleci/hugo
orbs:
  hugo: circleci/hugo@0.4.1
version: 2.1
workflows:
  main:
    jobs:
      - hugo/build:
          html-proofer: true
          version: '0.55'

