# from: https://circleci.com/orbs/registry/orb/circleci/hugo
jobs:
  deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/_build
      - run:
          name: Disable jekyll builds
          command: touch public/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@helias-constructions.com"
            git config user.name "ci-build"
      - run:
          name: Add custom domain
          command: echo "helias-constructions.com" > public/CNAME
      - add_ssh_keys:
          fingerprints:
            - "6b:19:27:c9:c5:39:de:ae:70:4f:f4:5e:b3:8c:3c:eb"
      - run:
          name: Deploy public websites to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Deploy in production" --dist public


orbs:
  hugo: circleci/hugo@0.4.1
version: 2.1
workflows:
  main:
    jobs:
      - hugo/build:
          html-proofer: false
          version: '0.68.3'
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - hugo/build

