# from: https://circleci.com/orbs/registry/orb/circleci/hugo
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - run: hugo -v
  deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@helias-constructions.com"
            git config user.name "ci-build"
      - run:
          name: Add custom domain
          command: echo "helias-constructions.com" > public/CNAME
      - add_ssh_keys:
          fingerprints:
            - "6b:19:27:c9:c5:39:de:ae:70:4f:f4:5e:b3:8c:3c:eb"

      - run:
          name: List build files
          command: ls docs
      - run:
          name: Deploy public websites to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Deploy at $(date)" --dist docs

version: 2.1
workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build

